### ISSUE TITLE
Grunt File not auto-compiling less stylesheets

### ISSUE THREAD

**Issue by dwinnbrown** [bambattajb/WF-Scaffold#1]
Grunt file doesn't auto-compile less style sheets added in to the `main.less` file via the `@import` statement: e.g. `@import "template_styles/template_one.less";`

Terminal session has to be stopped and re-started with `grunt serve` for `bundle.css` to be recompiled with new styles.

**Comment by bambattajb** [comment]
Added less watch task to `Gruntfile.js`. Watch now observes `.less` changes in `_dev.`

Reload triggered when `bundle.css` has changed in `_site`.
