### ISSUE TITLE
Not possible to use modular jQuery-UI

### ISSUE THREAD

**Issue by dwinnbrown** [bambattajb/WF-Scaffold#5]
The complete jQuery-UI library must be loaded to use specific 'widgets'.

**Comment by bambattajb** [comment]
The problem is jQuery UI assumes that the library is being called from a path relative to its root but we have explicitly stated the path for all JavaScript in our requirejs watch task.

To get jQuery UI to work specifically, we can do the following

**In require.config**
````
require.config({
    paths: {
        'jquery-ui' : 'lib/jquery-ui/ui',
    }
});
````
**In template**
````
define(['jquery', '**jquery-ui/widgets/tabs**'], function($) {
    console.log('JQ : ' + $);
    console.log('JQ :' + $('html').tabs())
});
````
